[build]
  base = "."
  publish = "./"
  functions = "./functions"
  command = ""
[build.environment]
  # Change this path with the path to your repository
  GO_IMPORT_PATH = "github.com/dylantackoor/packagema.in"
